### ISSUE TITLE
bug： List is not goroutine-safe 

### ISSUE THREAD

**Issue by liyue201** [douyu/juno-agent#5]
https://github.com/douyu/juno-agent/blob/cfb5d4a473512239fd42ebe624339df3900049bd/pkg/proxy/confProxy/etcd/etcd.go#L221

**Comment by younglifestyle** [comment]
确实，这里无法保证线程安全，不过官方重心应该还在框架上

**Comment by zhangmingke** [comment]
> https://github.com/douyu/juno-agent/blob/cfb5d4a473512239fd42ebe624339df3900049bd/pkg/proxy/confProxy/etcd/etcd.go#L221

好的，我们看下
